"""Specification for the final output dataframe."""

FINAL_NAME_MAP = {
    'nsc_code': '经销商ID',
    'date': '日期',
    'level': '层级',
    'store_name': '门店名',
    'natural_leads': '自然线索量',
    'paid_leads': '付费线索量',
    'local_leads': '本地线索量',
    'cloud_store_paid_leads': '车云店付费线索量',
    'regional_paid_leads': '区域加码付费线索量',
    'total_leads': '线索总量',
    'total_paid_leads': '直播车云店+区域付费线索量',
    'msg_private_entrants': '进私人数',
    'msg_active_consultations': '私信开口人数',
    'msg_leads_from_private': '咨询留资人数',
    'video_anchor_exposures': '锚点曝光量',
    'video_anchor_clicks': '组件点击次数',
    'video_new_posts': '短视频条数',
    'video_form_leads': '组件留资人数（获取线索量）',
    'live_gt_25min_duration_min': '超25分钟直播时长(分)',
    'live_effective_duration_hr': '直播时长',
    'live_gt_25min_sessions': '有效直播场次',
    'live_exposures': '曝光人数',
    'live_views': '场观',
    'live_widget_clicks': '小风车点击次数',
    'leads_from_live_form': '小风车留资量',
    'account_bi_live_form_leads': '直播线索量',
    'account_bi_video_views': '短视频播放量',
    'spending_net': '车云店+区域投放总金额',
    'effective_days': '有效天数',
    'level_nsc_count': '(层级维度)门店数',
    'cpl_total': '车云店+区域综合CPL',
    'cpl_paid': '付费CPL（车云店+区域）',
    'local_leads_ratio': '本地线索占比',
    'live_cpl': '直播付费CPL',
    'exposure_to_view_ratio': '曝光进入率',
    'widget_click_ratio': '小风车点击率',
    'widget_lead_ratio': '小风车点击留资率',
    'component_click_ratio': '组件点击率',
    'component_lead_ratio': '组件留资率',
    'private_msg_consult_ratio': '私信咨询率=开口/进私',
    'consult_to_lead_ratio': '咨询留资率=留资/咨询',
    'private_msg_conversion_ratio': '私信转化率=留资/进私',
    'avg_exposure_per_session': '场均曝光人数',
    'avg_view_per_session': '场均场观',
    'avg_widget_leads_per_session': '场均小风车留资量',
    'avg_widget_clicks_per_session': '场均小风车点击次数',
    'avg_daily_spending': '直播车云店+区域日均消耗',
    'avg_daily_effective_duration_hr': '日均有效（25min以上）时长（h）',
    'avg_daily_private_entrants': '日均进私人数',
    'avg_daily_active_consultations': '日均私信开口人数',
    'avg_daily_msg_leads': '日均咨询留资人数',
}

# This list defines the exact column order in the final output
OUTPUT_ORDER = list(FINAL_NAME_MAP.keys()) # Simple case: order is the same as the map keys
